### PR TITLE
Fixes #389

### LINKED ISSUE #389: Filter Issue When Editing Scenarios
The filters are not sticking when I try to edit multiple regressions in one session. To replicate, in the NSS page:

1. Select "Test" region
2. Filter the scenarios down further (select a stat group, reg region or statistic)
3. Hit "Edit Scenarios"
4. Select the "Edit" button next to a regression
5. Close the edit scenario window (by either canceling or saving edits)
6. Hit "edit" next to another regression
7. Close out and look at the scenarios on the page. Your filters are no longer applied.

### PR DESCRIPTION
**Pull request by harper-wavra**
- Added `saveFilters()` and `requeryFilters()` in order to save the sidebar filters and then reuse them when the scenario is saved or canceled.
- Removed extra `/` between `baseURL` and `scenriosURL`
- Sends `skipCheck` through as false when `check` is null on default
- Removed unused functions in sidebar component
- Removed `console.log` in manage citations component

### CODE REVIEW

File: src/app/shared/components/addscenario/addscenario.component.ts [hunk 1]
```diff
@@ -171,8 +171,28 @@ export class AddScenarioModal implements OnInit, OnDestroy {
...
+            this._nssService.setSelectedRegion(this.selectedRegion);
+            this._nssService.selectedStatGroups = [];
+            this._nssService.setSelectedRegRegions([]);
+            this._nssService.selectedRegressionTypes = [];
+        }
+    }
+
+    public equationCheck(check) {
+        if (check) { this.skipCheck = check; } 
+        else { this.skipCheck = false; }    //check for null
```
Comment (kjacobsen16) [inline src/app/shared/components/addscenario/addscenario.component.ts:195]: Fun tip: you can do one line true/false statements using the [ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator). 

Something like: `check ? this.skipCheck = check : this.skipCheck = false;`

**Review by kjacobsen16 — APPROVED** [review]
Looks good

File: src/app/shared/components/addscenario/addscenario.component.ts (hunk 1 above)
Comment (harper-wavra) [reply src/app/shared/components/addscenario/addscenario.component.ts:195]: Ahh I thought I could do a one line statement but couldn't find it when I googled it, thanks!
