### PR TITLE
Fixes #132

### LINKED ISSUE #132: Enable assigning new Region on Clone Scenario
Add option to change the region for a scenario when cloning, which means the regression regions will also need to update

### PR DESCRIPTION
**Pull request by harper-wavra**
Now able to clone an equation for a different region.

### CODE REVIEW

File: src/app/shared/components/addscenario/addscenario.component.ts [hunk 1]
```diff
@@ -42,8 +43,9 @@ export class AddScenarioModal implements OnInit, OnDestroy {
     public cloneParameters: any;
     public regRegion: any;
     public statisticGroup: any;
-    public clone: boolean;
+    public clone: boolean = false;
```
Comment (kjacobsen16) [inline src/app/shared/components/addscenario/addscenario.component.ts]: This is fine, but for future reference you don't need to type set it if you're setting an initial value. So just saying `public clone = false;` would have been fine :)

File: src/app/shared/components/addscenario/addscenario.component.ts [hunk 2]
```diff
@@ -42,8 +43,9 @@ export class AddScenarioModal implements OnInit, OnDestroy {
...
     public selectedRegion;
+    public orgRegion;
```
Comment (kjacobsen16) [inline src/app/shared/components/addscenario/addscenario.component.ts]: Is this short for "original region"? maybe this should be changed to `originalRegion`

File: src/app/shared/components/addscenario/addscenario.component.ts [hunk 3]
```diff
@@ -53,6 +55,7 @@ export class AddScenarioModal implements OnInit, OnDestroy {
         private _settingsService: SettingsService, private _configService: ConfigService, private _toasterService: ToasterService,
         private _authService: AuthService) {
         this.newScenForm = _fb.group({
+            'regionid': new FormControl(null, Validators.required),
```
Comment (kjacobsen16) [inline src/app/shared/components/addscenario/addscenario.component.ts]: You're actually setting this to the whole region, so the property should probably be named `region` instead

File: src/app/shared/components/addscenario/addscenario.component.html [hunk 4]
```diff
@@ -1,21 +1,31 @@
...
     <div class="modal-body">
         <form [formGroup]="newScenForm">
+
+            <!-- Clone - choose region -->
+            <div class="form-group" *ngIf="clone==true">
+                <label class="req" for="regionid">Region:</label>
+                <select class="form-control" formControlName="regionid">
+                    <option *ngFor="let r of regions" [ngValue]="r">{{r.name}}</option>
+                </select>
+            </div>
```
Comment (kjacobsen16) [inline src/app/shared/components/addscenario/addscenario.component.html]: I think is fine, but I'm wondering if it could have been done outside of the form (so placed after line 11 instead), and just hooked up to adjust the `selectedRegion` variable, so you don't have to add it to, and remove it from, the form.

**Review by kjacobsen16 — CHANGES_REQUESTED** [review]
Works well. I left a couple comments. There is one issue where the region sort of updates after you clone to a new region. The mainview component shows the new region, but the sidebar doesn't show it. It seems like either it's not sending the new region through correctly, or the sidebar isn't subscribing to the `selectedRegion` observable from the app.service correctly.

**Comment by harper-wavra** [comment]
In response to "The mainview component shows the new region, but the sidebar doesn't show it", after cloning to a new region do we want the mainview and sidebar to show the new region or the original region?

**Comment by kjacobsen16** [comment]
We should show the new region so they can see the new equation. I checked this with Ryan and he agrees.

**Review by kjacobsen16 — APPROVED** [review]
Works great - I think this will be an exciting one to have finished!
