### PR TITLE
Fixes #348

### LINKED ISSUE #348: Changes to edit scenario
I think the way we edit regression equations should be adapted to make the full scenario editable in one go.

Since we're already cloning the scenarios, I think we can do a similar thing where we send through the scenario to edit to the add scenario modal and instead of cloning, we let them edit and save when done.

### PR DESCRIPTION
**Pull request by harper-wavra**
When editing regression equations the full scenario is now editable in one go.

I tested my changes in the Test region and it seemed to be working how I thought it should without giving me any errors. However, there may be changes/comments on this if I wasn't thinking about it 100% correctly.

### CODE REVIEW

**Comment by harper-wavra** [comment]
If any of the key defining features are changed the scenario is cloned instead of edited. When any of those three core dropdowns are changed, I alerted the user with a toast message. There might be a better way then the toast message because if the user changes a dropdown then changes it back the message is similar and they might miss it. 

I tested my changes in the Test region and it seemed to be working how I thought it should without giving me any errors. However, I am expecting changes/comments on this if I wasn't thinking about it 100% correctly.

File: src/app/mainview/mainview.component.ts [hunk 1]
```diff
@@ -1222,6 +1222,13 @@ export class MainviewComponent implements OnInit {
     }
 
     /////////////////////// Edit Scenarios Section ///////////////////////////
+    public editScenarioRowClicked(statisticGroupID, r, rr) {
+        let info = 'edit';
+        this.cloneScen = { r, rr, statisticGroupID, info };
+        this.newCloneScenario(this.cloneScen);
+        this.showCloneScenarioModal();
```
Comment (kjacobsen16) [inline src/app/mainview/mainview.component.ts]: A couple things to clean up here:
1. You can just make lines 1225-1226 into one line: `this.cloneScen = { r, rr, statisticGroupID, 'edit' }`, or you can just combine this whole function with the `cloneRowClicked` function and send the `info` variable in the function call.
2. `newCloneScenario(...)` is a one-line function and it's only called twice (once if you combine this with cloneRowClicked), so you can just pull that line out and remove the function

File: src/app/shared/components/addscenario/addscenario.component.html [hunk 2]
```diff
@@ -299,7 +300,9 @@
 			<button type="button" (click)="clearScenario()" class="button red mright-xs">Clear All</button>
 			<button type="button" (click)="c('closed')" class="button black">Cancel</button>
 			<div class="flex-spacer"></div>
-			<button type="button" (click)="createNewScenario()" [disabled]="!newScenForm.valid" class="button blue">Create</button>
+			<button type="button" *ngIf="edit==false" (click)="createNewScenario()" [disabled]="!newScenForm.valid" class="button blue">Create</button>
+			<button type="button" *ngIf="edit==true" (click)="submitScenario()" [disabled]="!newScenForm.valid" class="button blue">Save</button>
```
Comment (kjacobsen16) [inline src/app/shared/components/addscenario/addscenario.component.html:304]: You could probably just combine these by using one function that has an if/else statement to see if edit = true

File: src/app/shared/components/addscenario/addscenario.component.ts [hunk 3]
```diff
@@ -58,6 +59,11 @@ export class AddScenarioModal implements OnInit, OnDestroy {
     public tempSelectedStatisticGrp: Array<Statisticgroup>;
     public filteredRegressionTypes;
     public filtered = true;
+    public scen;
+    public orgStatGrp;
+    public orgRegRegion;
+    public orgRegVariable;
```
Comment (kjacobsen16) [inline src/app/shared/components/addscenario/addscenario.component.ts]: I think just having an `originalScenario` variable would be a lot cleaner.

File: src/app/shared/components/addscenario/addscenario.component.ts [hunk 4]
```diff
@@ -182,16 +188,33 @@ export class AddScenarioModal implements OnInit, OnDestroy {
...
+            else if (this.cloneParameters.info == "edit"){
+                this.clearScenario();
+                this.clone = false;
+                this.edit = true;
+                this.filtered = false;
+                this.editMode = true;
+                this.orgStatGrp = this.cloneParameters.statisticGroupID;
+                this.orgRegRegion = this.cloneParameters.rr.id;
+                this.orgRegVariable = this.cloneParameters.r.id;
+                this.fillModal();
```
Comment (kjacobsen16) [inline src/app/shared/components/addscenario/addscenario.component.ts]: Some items are repeated between between the two if/else if statements (`thisClearScenario()`, `this.filtered = false`, etc.)

File: src/app/shared/components/addscenario/addscenario.component.ts [hunk 5]
```diff
@@ -58,6 +59,11 @@ export class AddScenarioModal implements OnInit, OnDestroy {
     public tempSelectedStatisticGrp: Array<Statisticgroup>;
     public filteredRegressionTypes;
     public filtered = true;
+    public scen;
+    public orgStatGrp;
+    public orgRegRegion;
+    public orgRegVariable;
+    public editMode: boolean;
```
Comment (kjacobsen16) [inline src/app/shared/components/addscenario/addscenario.component.ts:64]: Is this different than `edit`?

File: src/app/shared/components/addscenario/addscenario.component.ts [hunk 6]
```diff
@@ -287,10 +306,41 @@ export class AddScenarioModal implements OnInit, OnDestroy {
...
+        if (this.editMode == true){
+            this.scen = JSON.parse(JSON.stringify(this.newScenForm.value));
+            //change back to edit if user reselects original core dropdowns
+            if ((parameter == "statGroup" && this.orgStatGrp == this.scen.statisticGroupID) ||
+            (parameter == "regRegion" && this.orgRegRegion == this.scen.regressionRegions.ID) || 
+            (parameter == "regVariable" && this.orgRegVariable == this.scen.regressionRegions.regressions.ID)){
+                this.clone = false;
+                this.edit = true;
+                this._toasterService.clear();
+                this._toasterService.pop('info', 'Info', 'Scenario will be Edited Instead of Cloned');
```
Comment (kjacobsen16) [inline src/app/shared/components/addscenario/addscenario.component.ts]: Inconsistent capitalization here

File: src/app/shared/components/addscenario/addscenario.component.ts [hunk 7]
```diff
@@ -377,17 +427,47 @@ export class AddScenarioModal implements OnInit, OnDestroy {
...
+            .subscribe((response) => {
+                if (this.originalRegion == this.selectedRegion) {
+                    this._nssService.selectedStatGroups = this.tempSelectedStatisticGrp;
+                    this._nssService.setSelectedRegRegions(this.tempSelectedRegressionRegion);
+                    this._nssService.selectedRegressionTypes = this.tempSelectedRegType;
+                } else {
+                    this._nssService.setSelectedRegion(this.selectedRegion);
+                    this._nssService.selectedStatGroups = [];
+                    this._nssService.setSelectedRegRegions([]);
+                    this._nssService.selectedRegressionTypes = [];
```
Comment (kjacobsen16) [inline src/app/shared/components/addscenario/addscenario.component.ts]: This could be made into a separate function, because this is pretty much exactly what is called after the postentity in `createNewScenario`. Generally the way I treat functions is: if you're calling more than a couple lines more than once, it's easier to create a function. If you're calling just one or two lines, usually it's a waste of a function.

**Review by kjacobsen16 — CHANGES_REQUESTED** [review]
Overall works great - I think this is a big improvement!

This is probably an edge case but I did some playing around with the selects and if I change two of the core identifying properties to new items and then change only one of them back, it says it'll be "edited, not cloned", when at that point since there's still one different item it should be cloned.

The rest of my comments are just basic cleanup, they're not required.

File: src/app/shared/components/addscenario/addscenario.component.ts (hunk 6 above)
Comment (harper-wavra) [reply src/app/shared/components/addscenario/addscenario.component.ts]: Do you mean the info's or the 'Scenario will be Edited Instead of Cloned'?

File: src/app/shared/components/addscenario/addscenario.component.ts (hunk 5 above)
Comment (harper-wavra) [reply src/app/shared/components/addscenario/addscenario.component.ts:64]: It is different, yes.

File: src/app/shared/components/addscenario/addscenario.component.ts (hunk 6 above)
Comment (kjacobsen16) [reply src/app/shared/components/addscenario/addscenario.component.ts]: I was referring to "Scenario will be Edited Instead of Cloned", as well as the "...Cloned Instead of Edited"

**Review by kjacobsen16 — APPROVED** [review]
Works great!
