### PR TITLE
Fixes #220

### LINKED ISSUE #220: Issues with "removing" citation from new regression region modal
If I go to create a new regression region, hit "add new citation" then try removing it, I get an error.

Additionally, if I remove a citation then hit "Save", the citation isn't being completely removed. It's removed until I hit save, then assigned back to the regression region. I'm guessing the citation ID isn't being overwritten properly.

Maybe we shouldn't remove the citation before they hit save like it's currently doing - I know it messes up the list of citations in the manager citations modal, but the user should understand that they haven't saved yet so it's still assigned.

### PR DESCRIPTION
**Pull request by harper-wavra**
Solves issue #220 as well as issue when cloning a scenario and choosing a new region the regression regions drop down list didn't update for the new region selected.

### CODE REVIEW

File: src/app/shared/components/addregressionregion/addregressionregion.component.ts [hunk 1]
```diff
@@ -339,60 +340,70 @@ export class AddRegressionRegionModal implements OnInit, OnDestroy {
...
+              this.requeryFilters();
+              this._nssService.outputWimMessages(response);
+            }, error => {
+              if (this._settingsService.outputWimMessages(error)) {return; }
+              this._toasterService.pop('error', 'Error removing Citation', error._body.message || error.statusText);
+            }
+          );
+          this.selectedRegRegion.citationID = null;
+          this.cancelCreateRegression();
+        }
```
Comment (kjacobsen16) [inline src/app/shared/components/addregressionregion/addregressionregion.component.ts]: Instead of doing a whole other `putEntity` call here, your `removeCitation` function should be changing the citation ID to null for the reg region, which will go through the putEntity call used to update the reg region. In that case, this whole section can be removed.

File: src/app/shared/components/addscenario/addscenario.component.ts [hunk 2]
```diff
@@ -198,6 +198,12 @@ export class AddScenarioModal implements OnInit, OnDestroy {
         this.newScenForm.get('region').valueChanges.subscribe(item => {
              if(item != null){
                 this.selectedRegion = item;
```
Comment (kjacobsen16) [inline src/app/shared/components/addscenario/addscenario.component.ts]: If we change this to `this._nssService.setSelectedRegion(item);`, it'll update the regression regions _and_ the selected region, which means we won't need lines 202-205

File: src/app/shared/components/addregressionregion/addregressionregion.component.ts [hunk 3]
```diff
@@ -339,60 +340,70 @@ export class AddRegressionRegionModal implements OnInit, OnDestroy {
...
-            this.requeryFilters();
-            this._nssService.outputWimMessages(response);
-        }, error => {
-            if (this._settingsService.outputWimMessages(error)) {return; }
-            this._toasterService.pop('error', 'Error removing Citation', error._body.message || error.statusText);
-        }
-    );
-    this.selectedRegRegion.citationID=null;
+    if (this.selectedRegRegion) { // if creating new regression region cannot set citationID to null
+      this.selectedRegRegion.citationID = null
```
Comment (kjacobsen16) [inline src/app/shared/components/addregressionregion/addregressionregion.component.ts:383]: This needs to change the citation ID of the newRegReg form. Otherwise, it doesn't get sent through when saving the reg region.

**Review by kjacobsen16 — CHANGES_REQUESTED** [review]
In general, things are working but there are a few places where you're making additional calls that are unnecessary. Make sure to check that you're not replicating functions and calls, especially when it comes to things that we can set up subscribers for (e.g. selected region, reg regions, etc.).

**Review by kjacobsen16 — APPROVED** [review]
Everything appears to be working great!
